Document,Location,Source,Failure,Failure Explanation,Failure.1,Failure Explanation.1
CISG,"Article 8(3) (This article is essentially a pragmatics textbook. Contains: intent reasonable person practices usages subsequent conduct For Italian and Turkish this is extremely challenging because the legal concept of the ""reasonable person"" is not lexicalized identically) (Pragmatics, intention, reasonable person)","In determining the intent of a party or the understanding a reasonable person would have had, due consideration is to be given to all relevant circumstances of the case including the negotiations, any practices which the parties have established between themselves, usages and any subsequent conduct of the parties.","Semantic failure 
Source: “including the negotiations, any practices which the parties have established between themselves, usages…”
MT: “müzakereler… uygulamalar, gelenekler…”
The MT partially preserves the literal meaning but weakens the legal distinction between practices, usages, and general customs/traditions.
Pragmatic failure 
The sentence sounds less like an international commercial law provision and more like a general explanatory sentence. The legal-pragmatic force of established commercial practice is weakened.","The Turkish MT weakens the legal specificity of the source by translating “negotiations” simply as “müzakereler”, without making clear that these are contractual negotiations between the parties. In legal context, this may sound too general. In addition, “usages” is rendered as “gelenekler”, which is pragmatically too everyday and culturally broad. The official HT’s “teamüller” is more appropriate because it refers to legally and commercially relevant practices.","Semantic failure 
The Italian MT translates “understanding” as “interpretazione”, while the HT uses “ciò che avrebbe inteso una persona ragionevole”. “Interpretazione” is not entirely wrong, but it narrows the meaning toward legal interpretation rather than the reasonable person’s understanding.
Pragmatic failure
The MT expression “qualsiasi prassi” is understandable, but less institutionally polished than the HT’s “consuetudini fra di esse stabilitesi”. The MT is accurate overall, but less conventional in legal drafting.","HT: ciò che avrebbe inteso una persona ragionevole
MT: interpretazione
The MT shifts the meaning toward legal interpretation rather than reasonable understanding. A subtle but important legal distinction is weakened.The conventional legal phrasing of the CISG is weakened. The MT sounds more like an explanatory translation than treaty language."
CISG,Article 25 (Contains fundamental breach detriment entitled to expect foreseeability reasonable person This is one of the most semantically dense sentences in the whole Convention) (Fundamental breach + foreseeability),"A breach of contract committed by one of the parties is fundamental if it results in such detriment to the other party as substantially to deprive him of what he is entitled to expect under the contract, unless the party in breach did not foresee and a reasonable person of the same kind in the same circumstances would not have foreseen such a result.","Semantic failure
Source: “unless the party in breach did not foresee and a reasonable person… would not have foreseen such a result.”
MT: “...hariç sonucu öngöremezdi.”
The exception clause is structurally broken. The MT does not clearly express the cumulative condition: the breaching party did not foresee the result, and a reasonable person would not have foreseen it either. The foreseeability exception is not properly expressed. The MT breaks the logical relationship between breach, foreseeability, and liability. The legal meaning becomes incomplete.
Pragmatic failure
The provision loses its authoritative legal force. The MT sounds like an unfinished explanatory paraphrase rather than a binding legal norm. The provision loses legislative authority because the sentence becomes grammatically fragmented. The MT reads as an unfinished explanation rather than a binding legal norm.","The Turkish MT is syntactically and legally defective. It contains a repeated and awkward structure: “sözleşme kapsamında hak ettiği beklentileri önemli ölçüde sözleşme kapsamında hak ettiği şeyden mahrum bırakacak…”. This repetition disrupts the legal logic of the sentence. More seriously, the final clause “sonucu öngöremezdi” is not integrated into a proper legal conditional structure. The source expresses an exception to liability based on foreseeability, whereas the MT leaves the clause grammatically unfinished and pragmatically weak.","Semantic failure
The Italian MT translates “fundamental” as “grave”, while the HT uses “essenziale”. This is a significant terminological issue. In CISG discourse, “fundamental breach” is a specific legal concept, and “violazione grave” is broader and less technical than “inosservanza essenziale”. There is also a visible duplication: “da da privarla”, which damages grammatical quality. The CISG concept of fundamental breach is rendered as a more general notion of serious breach. A specialized legal concept is replaced by a broader and less technical term.
Pragmatic failure
The MT weakens the institutional terminology of CISG. By using “grave” instead of a more conventional equivalent of “fundamental,” the sentence loses part of its doctrinal precision. The established CISG terminology is weakened.
Legal certainty depends on the consistent use of technical concepts, and the MT disrupts that consistency.","HT: inosservanza essenziale
MT: violazione grave
The CISG concept of fundamental breach is replaced by a more general concept of serious breach.
A specialized legal term is replaced by a broader one. The established CISG terminology is weakened.
Legal discourse relies heavily on terminological consistency, and the MT disrupts that consistency."
CISG,"Article 35(2)(b) (perfect for: implied meaning, reliance, reasonableness, seller's skill and judgement. Huge pragmatic component) (Implied purpose + reliance)","Except where the parties have agreed otherwise, the goods do not conform with the contract unless they: (b) are fit for any particular purpose expressly or impliedly made known to the seller at the time of the conclusion of the contract, except where the circumstances show that the buyer did not rely, or that it was unreasonable for him to rely, on the seller’s skill and judgement;","Semantic failure
Source: “did not rely… on the seller’s skill and judgement”
MT: “satıcının beyanına güvenmediğini veya satıcının beceri ve muhakemesine güvenmesinin…”
The addition of “beyan” introduces a concept not present in the source. The issue is not reliance on a declaration, but reliance on professional competence and judgement. Source: seller's skill and judgement
MT: satıcının beyanı
The MT introduces a concept not present in the source. Reliance on professional expertise becomes reliance on a statement or declaration. This changes the legal meaning.
Pragmatic failure 
The MT fails to reproduce the carefully balanced legal exception. It sounds overloaded and unclear, reducing the interpretive precision of the provision. The legal exception becomes difficult to process because of excessive syntactic complexity. The balance between conformity and non-conformity conditions is weakened.","The official Turkish HT strategically restructures the negative English formulation into a positive legal formulation: goods are conforming only if they meet the listed conditions. This improves legal readability. The MT keeps the negative structure too closely and produces a syntactically heavy sentence. In addition, “satıcının beyanına güvenmediğini” is a semantic error because the source refers to reliance on the seller’s skill and judgement, not on the seller’s statement or declaration.","Semantic failure
The Italian MT is mostly accurate. However, “beni” is less conventional than “merci” in CISG/commercial sales discourse. Also, the structure “non sono conformi… a meno che” is closer to the English but less smooth than the HT’s positive restructuring: “sono conformi… solo se”. The MT is generally accurate but weakens established CISG terminology by using less conventional commercial-law wording.
Pragmatic failure
The MT is legally understandable, but less elegant and less conventional than the official translation. The HT better reflects Italian legislative drafting style. The provision remains understandable but sounds less like legislative drafting and more like a literal translation.",
CISG,"Article 79(1) (The CISG force majeure provision. Contains impediment, reasonably expected, avoided or overcome, consequences. Very difficult in Turkish legal translation) (Force majeure language)","A party is not liable for a failure to perform any of his obligations if he proves that the failure was due to an impediment beyond his control and that he could not reasonably be expected to have taken the impediment into account at the time of the conclusion of the contract or to have avoided or overcome it, or its consequences.","Semantic failure
Source: “A party is not liable… if he proves that…”
MT: “Bir taraf… kaynaklandığını ve… beklenemezdi.”
The MT fails to express the full conditional relationship between proof, impediment, reasonable expectation, avoidance, and exemption from liability. The exemption from liability is not properly connected to the conditions that follow. The logical chain between proof, impediment, foreseeability, and exemption becomes unclear.
Pragmatic failure
This is one of the strongest failures. A force majeure provision must be precise and authoritative. The MT instead sounds incomplete, ungrammatical, and unreliable as legal language. The legal rule becomes difficult to identify. The MT lacks the certainty and authority expected from an international treaty provision.","The Turkish MT is severely defective because the sentence lacks a complete legal predicate. The source establishes a condition under which a party is not liable for non-performance. The MT states several conditions but fails to connect them properly to the conclusion of non-liability. The phrase “beklenemezdi” appears without a clear legal frame, making the sentence grammatically incomplete and legally unclear.","Semantic failure
The Italian MT is mostly understandable, but the clause “o di averlo evitato o superato” is structurally problematic. It may imply that the party actually avoided or overcame the impediment, whereas the source says the party could not reasonably be expected to have avoided or overcome it. The MT creates ambiguity regarding whether the impediment was actually avoided or overcome. The source states that the party could not reasonably be expected to avoid or overcome the impediment. The MT weakens this distinction.
Pragmatic failure 
The MT weakens the logical sequence of force majeure reasoning. It is less defective than the Turkish MT, but it still creates ambiguity in a provision where legal causality and reasonable expectation are central. The causal structure underlying the force majeure exception becomes less transparent. The MT weakens the institutional precision of the provision.",
CISG,"Article 9(2) (This is arguably the most difficult sentence syntactically. Contains: impliedly usage ought to have known regularly observed and multiple embedded relative clauses) (Custom, usage, embedded clauses)","The parties are considered, unless otherwise agreed, to have impliedly made applicable to their contract or its formation a usage of which the parties knew or ought to have known and which in international trade is widely known to, and regularly observed by, parties to contracts of the type involved in the particular trade concerned.","Semantic failure
Source: “to have impliedly made applicable to their contract or its formation a usage…”
MT: “bir teamülü, sözleşmelerine veya sözleşmenin akdedilmesine zımnen uygulamış sayılırlar.”
The MT blurs the distinction between making a usage applicable and actually applying it. Source: impliedly made applicable
MT: zımnen uygulamış sayılırlar
The source concerns the implied incorporation of a trade usage into the contract. The MT suggests that the parties actually applied the usage. The legal meaning shifts.
Pragmatic failure
The provision loses legal clarity. The reader can understand the general idea, but the drafting is heavy and unnatural. The heavy syntax obscures the legal presumption established by the provision. The institutional clarity of the rule is reduced.","The Turkish MT is syntactically overloaded and less idiomatic than the HT. The source contains several embedded clauses: the parties knew or ought to have known the usage; the usage is widely known in international trade; and it is regularly observed by parties to contracts of that type in the relevant trade. The MT attempts to preserve all clauses, but the result is difficult to process. In addition, “zımnen uygulamış sayılırlar” is less accurate than the HT’s “uygulanmasını zımnen kabul ettikleri varsayılır”, because the source concerns implied incorporation into the contract, not the parties themselves “applying” the usage.","Semantic failure
The Italian MT is mostly accurate, but “abbiano implicitamente applicato” has the same problem as the Turkish MT: it suggests that the parties applied the usage, whereas the source says they are considered to have made it applicable to the contract or its formation. The HT’s “si siano tacitamente riferite” better captures implied incorporation. HT: si siano tacitamente riferite
MT: abbiano implicitamente applicato
The MT again shifts from implied incorporation to actual application. The legal relationship between the parties and the trade usage is altered.
Pragmatic failure  
The MT is readable but less legally elegant. The phrase “del tipo oggetto del settore commerciale in questione” is awkward and less natural than the HT’s “nel ramo commerciale considerato.” The sentence remains understandable but loses the concise legal style of the HT. The provision sounds more explanatory than normative.","HT: si siano tacitamente riferite
MT: abbiano implicitamente applicato 
The same shift occurs. The source concerns incorporation. The MT suggests application. The legal relationship between parties and trade usage is altered. The MT sounds explanatory rather than normative. The concise style typical of legal drafting is weakened."
ECHR,"Article 8(2) (necessary in a democratic society, “interference,” proportionality, vague public-interest grounds)","There shall be no interference by a public authority with the exercise of this right except such as is in accordance with the law and is necessary in a democratic society in the interests of national security, public safety or the economic well-being of the country, for the prevention of disorder or crime, for the protection of health or morals, or for the protection of the rights and freedoms of others.","Semantic failure
Source: There shall be no interference ...
MT: müdahaleler dışında müdahale edemez
The prohibition structure becomes blurred.
Pragmatic failure
The legal norm loses authority. The sentence sounds translated rather than legislatively drafted.","The MT creates a heavy and circular structure through “müdahaleler dışında müdahale edemez”, which weakens legal readability. The sentence also shifts the syntactic focus from the prohibition of interference to the public authorities as active agents. Semantically, “kargaşa” is weaker and less institutional than the legal concept of “düzenin bozulması / kamu düzeni”. Pragmatically, the MT reduces the formal Convention style and makes the proportionality logic less transparent.","Semantic failure
Official HT: ingerenza
MT: interferenza
Although close in ordinary language, they are not equally conventional in ECHR legal discourse. A specialized legal term is replaced by a more general one.
Pragmatic failure
The established ECHR phraseology is weakened. Institutional legal discourse relies heavily on consistency of terminology. The MT disrupts that consistency.","The Italian MT is mostly accurate. However, “interferenza” is less legally conventional than “ingerenza” in ECHR terminology. The phrase “salvo quelle previste” is slightly imprecise because it refers back to “interferences” rather than clearly to legally justified interference. Pragmatically, it is acceptable but less idiomatic than the HT."
ECHR,"Article 15(1) (derogation, emergency language, “strictly required by the exigencies', perfect for semantic ambiguity the word exigency)","In time of war or other public emergency threatening the life of the nation any High Contracting Party may take measures derogating from its obligations under this Convention to the extent strictly required by the exigencies of the situation, provided that such measures are not inconsistent with its other obligations under international law.","Semantic failure
The source states: ""to the extent strictly required by the exigencies of the situation""
MT: ""durumun gerektirdiği ölçüde""
The notion of strict necessity disappears. This alters the legal threshold for derogation.
Pragmatic failure
Article 15 is intentionally restrictive. The MT weakens the force of state obligations during emergencies. The institutional warning against governmental abuse becomes less explicit.","“Sapma niteliğinde tedbirler” sounds unnatural and is not the best legal equivalent for derogation. More importantly, the MT omits the force of “strictly required” by translating it only as “durumun gerektirdiği ölçüde”. This is a semantic loss because the original imposes a strict necessity threshold. Pragmatically, the exceptional nature of emergency derogation is weakened.","Semantic failure
The HT uses: ""pericolo pubblico che minacci la vita della nazione""
MT: ""emergenza pubblica che minacci la sopravvivenza della nazione""
Two shifts occur:
•	life → survival 
•	danger → emergency 
Neither is catastrophic individually, but together they move away from the established ECHR legal formula.
Pragmatic failure
The Convention deliberately employs fixed legal phraseology. Changing established legal formulas affects intertextual consistency with ECHR jurisprudence. The institutional voice becomes less precise.","The Italian MT is quite accurate and even preserves “strettamente richiesta”. However, “emergenza pubblica” is less aligned with the HT’s “pericolo pubblico”. “Sopravvivenza della nazione” is slightly interpretive compared with “vita della nazione”, but it does not seriously distort the meaning. Pragmatically, the emergency logic is preserved."
ECHR,"Article 6(1) (fair trial terminology, exceptions, “prejudice the interests of justice')","In the determination of his civil rights and obligations or of any criminal charge against him, everyone is entitled to a fair and public hearing within a reasonable time by an independent and impartial tribunal established by law. Judgment shall be pronounced publicly but the press and public may be excluded from all or part of the trial in the interests of morals, public order or national security in a democratic society, where the interests of juveniles or the protection of the private life of the parties so require, or to the extent strictly necessary in the opinion of the court in special circumstances where publicity would prejudice the interests of justice.","Semantic failure
Source: everyone is entitled to a fair and public hearing
MT: mahkeme tarafından yargılama hakkı vardır
The source text establishes an entitlement to a hearing conducted under specific guarantees of fairness, publicity, independence, and impartiality. The MT shifts the focus toward the act of being tried by a court, thereby reducing the emphasis on the procedural safeguards embedded in the notion of a ""fair and public hearing.""
Pragmatic failure
Article 6(1) functions as a rights-conferring legal provision. The MT weakens the performative force of the original by presenting the provision in a more procedural and descriptive manner. As a result, the authoritative institutional voice of the Convention is reduced, and the sentence sounds more like an explanation of judicial proceedings than a declaration of a fundamental right.","“Mahkeme tarafından ... yargılama hakkı vardır” is awkward because the person does not have a “trial by a court” in that syntactic form; they have the right to have the case heard by a lawful, independent, impartial tribunal. “Hakkı vardır” is also less formal than “hakkına sahiptir.” Semantically, the MT weakens the idea that the tribunal determines civil rights or the merits of a criminal charge. Pragmatically, it loses the official Convention style. “Kamuya açık olarak açıklanır” is repetitive and not legally idiomatic; “alenî olarak verilir/açıklanır” would be better. “Çocuklar” is less formal than “küçükler”, and “adaletin menfaatleri” is unnatural compared with “adil yargılamanın gerekleri / adaletin çıkarları.” Semantically, the MT preserves the general meaning, but the legal register is weakened. Pragmatically, the exception logic becomes harder to follow.","Semantic failure
Official HT: ha diritto a che la sua causa sia esaminata equamente, pubblicamente
MT: nel determinare ... ogni persona ha diritto a un'udienza equa e pubblica
Although the overall meaning is preserved, the MT restructures the sentence and weakens the direct relationship between the individual and the examination of their case. The explicit guarantee that one's case shall be heard under specified procedural conditions becomes less prominent.
Pragmatic failure
The official ECHR formulation employs a highly standardized legal phraseology that has become established through Convention jurisprudence. By restructuring the sentence and moving away from the conventional wording of the official translation, the MT weakens the institutional style characteristic of ECHR discourse. Although the legal content remains largely recoverable, the authoritative and rights-conferring function of the provision becomes less explicit.","The Italian MT is understandable but weaker than the HT. It begins with “Nel determinare...”, which sounds procedurally awkward. It also omits the fuller idea of “la sua causa sia esaminata”. Semantically, the right is preserved, but the legal framing is less precise. Pragmatically, the sentence sounds more like a general legal paraphrase than an official Convention formulation. Minor issue: “possono essere esclusi da tutto o parte del processo” is slightly less precise than the HT’s focus on access to the courtroom. However, the semantic and pragmatic content is largely preserved."
ECHR,"Article 35(3)(b) (admissibility threshold, exception logic, pragmatic vagueness of “significant”) (What is significant? Purely contextual. Excellent example of vagueness)","the applicant has not suffered a significant disadvantage, unless respect for human rights as defined in the Convention and the Protocols thereto requires an examination of the application on the merits.","Semantic failure
Source: significant disadvantage
MT: ciddi mağduriyet
These are not equivalent. Disadvantage ≠ victimhood. The admissibility criterion changes.
Pragmatic failure
The MT additionally inserts: Bu durum istisnadır. This adds interpretive information. The translator begins explaining the law instead of reproducing it.","“Bu durum istisnadır” adds an explanatory phrase that is not present in the source and distorts the exception logic. “İnsan haklarına saygı gereği” is also less legal than “insan haklarına saygı ilkesi.” Semantically, “ciddi mağduriyet” is not identical to “significant disadvantage”; it shifts the focus toward victimhood rather than disadvantage/prejudice. Pragmatically, the admissibility threshold becomes less precise.","Semantic failure 
Official HT: pregiudizio importante
MT: pregiudizio significativo
The difference seems small. However, ECHR admissibility criteria rely on fixed terminology. The MT departs from established legal wording.
Pragmatic failure
The MT becomes more explanatory and less formulaic than the official ECHR version. The institutional style of admissibility provisions is weakened.","The Italian MT is strong. “Pregiudizio significativo” is acceptable, though the official HT’s “pregiudizio importante” is closer to ECHR terminology. The clause “quali definiti nella Convenzione” follows the English closely. No major pragmatic failure appears."
GDPR,"Recital 23 (scope ambiguity, intention, “mere accessibility,” evidential reasoning)","Whereas the mere accessibility of the controller's, processor's or an intermediary's website in the Union, of an email address or of other contact details, or the use of a language generally used in the third country where the controller is established, is insufficient to ascertain such intention, factors such as the use of a language or a currency generally used in one or more Member States with the possibility of ordering goods and services in that other language, or the mentioning of customers or users who are in the Union, may make it apparent that the controller envisages offering goods or services to data subjects in the Union.","HT: Birlik içerisinden erişilebilen. MT: Birlik içindeki web sitesi. This creates a classic attachment problem. The MT suggests website located in the Union instead of website accessible from the Union. The legal criterion changes.
Semantic failure
The geographical scope becomes distorted. Location and accessibility are not equivalent concepts. This affects the interpretation of territorial applicability under GDPR.
Pragmatic failure
The sentence is trying to establish mere accessibility is insufficient evidence. The MT weakens the restrictive force of ‘mere accessibility’ and simultaneously strengthens ‘may make it apparent’ into ‘açıkça ortaya koyabilir’ which sounds more certain. Thus the evidential standard changes.","The Turkish MT produces an attachment ambiguity by rendering “website in the Union” as if the website itself were situated in the Union. This distorts the legal scope of the provision, because the English source refers to the mere accessibility of the website, email address or contact details within the Union. Moreover, the pragmatic emphasis of “mere accessibility” is weakened: the MT says “erişilebilir olması”, but does not fully preserve the restrictive force of “mere”, which is crucial because the sentence distinguishes insufficient evidence from factors that may indicate intention. The MT also strengthens “may make it apparent” into “açıkça ortaya koyabilir”, which is too strong. “May make it apparent” expresses evidential possibility, not certainty.","Italian is relatively good here. However, ‘possono rendere evidente’ is stronger than ‘may make it apparent’ and slightly increases certainty.","The Italian MT is generally good, but it slightly strengthens the evidential force with “possono rendere evidente”. This is acceptable but somewhat stronger than the source’s cautious “may make it apparent”. Also, “nel territorio dell’Unione” is clearer than the Turkish MT because it preserves the idea of accessibility within the Union rather than locating only the website there."
GDPR,"Article 9(2)(g) (“substantial public interest,” proportionality, essence of right, safeguards)","processing is necessary for reasons of substantial public interest, on the basis of Union or Member State law which shall be proportionate to the aim pursued, respect the essence of the right to data protection and provide for suitable and specific measures to safeguard the fundamental rights and the interests of the data subject;","Semantic failure
The Turkish MT transforms a nominalized legal condition into an independent conditional sentence. Source: processing is necessary for reasons of substantial public interest. HT: işlemenin ... gerekli olması. MT: işleme ... gerekli ise. The legal relationship changes. The source expresses a legal requirement embedded within a list of conditions. The MT creates a separate conditional statement.
Pragmatic failure
The GDPR provision functions as a legal authorization condition. The HT preserves this legislative drafting style. The MT turns it into something closer to an explanatory statement. As a result, the normative force is weakened. This is extremely important in legal discourse.","The Turkish MT converts a legal condition into an independent sentence. In the source, this is not a standalone statement but a condition within Article 9(2): processing is permitted only where this condition is satisfied. The HT correctly nominalizes the clause with “işlemenin gerekli olması”. By contrast, the MT’s “işleme … gerekli ise; bu hukuk … içermelidir” breaks the legislative structure and weakens the conditional function of the provision. Moreover, “onemli kamu yararı” is weaker than “esaslı kamu yararı” for “substantial public interest”. “Somut önlemler” does not fully match “specific measures”; “spesifik tedbirler” is closer in legal-technical register. ",‘in base al diritto’ is less legalistic than ‘sulla base del diritto’ and ‘adeguate’ does not fully reproduce ‘appropriate’.,"The Italian MT is accurate and even preserves the subjunctive “sia necessario”, which fits the conditional legal structure. Minor issue: “in base al diritto” is slightly less formal than “sulla base del diritto”. “Adeguate” is acceptable for “suitable”, but “appropriate” in the HT is closer to the source’s legal terminology."
GDPR,"Recital 71 (best one for AI/MT analysis; automated decision-making, legal effects, profiling)","The data subject should have the right not to be subject to a decision, which may include a measure, evaluating personal aspects relating to him or her which is based solely on automated processing and which produces legal effects concerning him or her or similarly significantly affects him or her, such as automatic refusal of an online credit application or e-recruiting practices without any human intervention.","The MT breaks the relationship between the examples and the legal statement. Source: such as automatic refusal of an online credit application or e-recruiting practices ... The examples are part of the legal definition. MT: Durumlar buna dahildir; ... The examples become explanatory additions. This changes the discourse structure.
Semantic impact
This is a classic case of: semantic narrowing. The legal scope becomes smaller than intended.
Pragmatic impact
The GDPR intentionally uses broad terminology. The MT unintentionally reduces interpretive flexibility. Thus it changes how the provision may be interpreted by readers.","The Turkish MT fails to integrate the examples into the legal sentence and instead separates them after a semicolon. This makes the examples sound explanatory rather than part of the legal scope of the provision. “Kişisel özellikler” also lowers the register and narrows the meaning of “personal aspects”; “kişisel veçheler” better preserves the abstract legal terminology. Finally, “e-işe alım” is overly literal and less natural than “çevrim içi işe alma uygulamaları”. Morever, “durumlar buna dahildir” is not present in the source and makes the sentence more explanatory than legislative. It reduces the precision of the original structure.","This is one of the clearest semantic errors in the entire dataset. HT: aspetti personali che lo riguardano. MT: aspetti della sua personalità. The source refers to professional aspects, economic aspects, behavioural aspects, health aspects, personal characteristics. The MT narrows the meaning to personality traits which is substantially more restrictive.
Semantic impact
This is a classic case of: semantic narrowing. The legal scope becomes smaller than intended.
Pragmatic impact
The GDPR intentionally uses broad terminology. The MT unintentionally reduces interpretive flexibility. Thus it changes how the provision may be interpreted by readers.","The Italian MT has a significant semantic issue: “aspetti della sua personalità” narrows “personal aspects relating to him or her” to personality traits. The source is broader and may include financial, professional, behavioural, or other personal aspects. The HT’s “aspetti personali che lo riguardano” is more accurate. “Reclutamento elettronico” is understandable but less natural than “pratiche di assunzione elettronica”."
GDPR,Article 49(1) (heavy conditional chain; perfect for testing whether MT preserves legal restriction),"Where a transfer could not be based on a provision in Article 45 or 46, including the provisions on binding corporate rules, and none of the derogations for a specific situation referred to in the first subparagraph of this paragraph is applicable, a transfer to a third country or an international organisation may take place only if the transfer is not repetitive, concerns only a limited number of data subjects, is necessary for the purposes of compelling legitimate interests pursued by the controller which are not overridden by the interests or rights and freedoms of the data subject, and the controller has assessed all the circumstances surrounding the data transfer and has on the basis of that assessment provided suitable safeguards with regard to the protection of personal data.","The MT reproduces the words, but the legal architecture becomes much less transparent. The most problematic segment is: ‘veri sorumlusunun veri sahibinin menfaatleri veya hak ve özgürlüklerinden üstün olmayan zorlayıcı meşru menfaatleri’. Literally: ‘the controller's compelling legitimate interests that are not superior to the interests or rights and freedoms of the data subject’. This creates ambiguity. The source means the controller has compelling legitimate interests AND the data subject's rights do not override those interests. The MT makes it look as if the legitimate interests themselves are ""not superior"". These are not the same thing.
Semantic failure
This is primarily a case of scope ambiguity.
The source: ‘compelling legitimate interests are not overridden by the interests or rights and freedoms of the data subject’ contains a legal balancing test. The MT obscures who outweigh whom, what is being compared, what the legal threshold is.  As a result, the balancing relationship becomes semantically unclear.
Pragmatic failure
This is where the example becomes interesting. The GDPR is not merely describing a situation. It is imposing legal restrictions. The source sentence guides legal interpretation through carefully layered conditions. The MT preserves the content but weakens the accessibility of those conditions. In legal discourse, clarity of dependency relations is essential because legal obligations are interpreted through those relations. Thus the MT produces a pragmatic failure by making the hierarchy of legal requirements harder to identify.","The Turkish MT preserves the general meaning, but the long sequence of conditions is less controlled than in the HT. The source imposes several cumulative requirements: the transfer must be non-repetitive, limited in scope, necessary for compelling legitimate interests, not overridden by the data subject’s rights and interests, and accompanied by safeguards. The MT’s structure makes these conditions harder to process. The phrase “veri sorumlusunun veri sahibinin menfaatleri veya hak ve özgürlüklerinden üstün olmayan zorlayıcı meşru menfaatleri” is especially problematic because it can be read as if the controller’s interests themselves are “not superior”, rather than saying that the data subject’s interests do not override them. Moreover, “tekrarlayıcı olmaması” is less legal than “yinelemeli olmaması”. “İstisnalar” is understandable, but “derogasyonlar” is more technical in EU-law contexts.","The Italian MT is actually more interesting than it first appears. The key phrase:
HT: interessi legittimi cogenti
MT: interessi legittimi preminenti
This is subtle but important.
Source
compelling legitimate interests
means:
•	strong 
•	pressing 
•	compelling 
MT
preminenti
suggests:
•	prevailing 
•	superior 
•	dominant 
The meaning shifts. The source does not say the controller's interests are already superior. It says they are compelling enough to justify consideration. The balancing test still has to be performed. The MT risks implying superiority before the balancing exercise takes place.","The Italian MT is mostly accurate, but there is one important semantic problem: “interessi legittimi preminenti” may overstate “compelling legitimate interests”. “Compelling” means strong/pressing, while “preminenti” suggests prevailing or superior. This matters because the same sentence later says these interests must not be overridden by the data subject’s rights and freedoms. The HT’s “interessi legittimi cogenti” is more precise."
